### ISSUE TITLE
DPSL-ASR数据集

### ISSUE THREAD

**Issue by glcamila** [YUCHEN005/RATS-Channel-A-Speech-Data#1]
![数据集](https://github.com/YUCHEN005/RATS-Channel-A-Speech-Data/assets/101648474/efc82dbc-258a-4a31-9e71-838d304971e6)

您好！请问这里的数据集是DPSL-ASR那个代码的数据集吗？

**Comment by YUCHEN005** [comment]
对的 rats channel-A数据集
